/** The closed roster of writes. The op table in ops.ts is keyed by it and a
 * work item's `next.op` is drawn from it, so a renamed op cannot leave a stale
 * intent behind. */
export const writeNames = [
	"business.configure",
	"employee.record",
	"compensation.budget",
	"compensation.assign",
	"election.document",
	"election.record",
	"question.ask",
	"question.answer",
	"policy.install",
	"policy.activate",
	"policy.annual",
	"policy.evidence",
	"policy.refresh",
	"filings.ensure",
	"filings.expect-retirement",
	"filings.prepare",
	"filings.submit",
	"filings.reject",
	"filings.deadline",
	"filings.amend",
	"mailing.record",
	"payment.record",
	"payment.reconcile",
	"payment.dispose",
	"payroll.calculate",
	"payroll.post",
	"payroll.revise-tax",
	"recovery.record",
	"artifact.record",
	"artifact.locate",
	"artifact.verify",
	"artifact.archive",
	"artifact.attach-bank",
	"bank.movement",
	"bank.distribution",
	"bank.distribution-return",
	"bank.distribution-review",
	"bank.payroll-cash",
	"retirement.plan",
	"retirement.account",
	"retirement.annual",
	"retirement.contribution",
	"retirement.authorize-after-tax",
	"retirement.cancel-authorization",
	"retirement.fund",
	"retirement.receipt",
	"retirement.allocate-receipt",
	"retirement.conversion",
	"retirement.supplied-tax",
	"retirement.supplied-report",
	"retirement.confirm-reported-conversion",
	"retirement.balance"
] as const
export type WriteName = (typeof writeNames)[number]
