/** Every integer that crosses the JSON boundary has exactly one unit, decided
 * by its field name. The name is the representation: the same name never
 * carries two units anywhere in the schema, inputs, or read models, and an
 * integer whose name is absent from this table refuses to cross the boundary.
 */
export const unitOf = {
	// Money: integer cents inside, "1234.56" dollars at the boundary.
	amount: "Money",
	gross: "Money",
	cash: "Money",
	cents: "Money",
	limit: "Money",
	maximum: "Money",
	deferralLimit: "Money",
	additionsLimit: "Money",
	compensationCap: "Money",
	outsideDeferrals: "Money",
	outsideAdditions: "Money",
	federalDepositLimit: "Money",
	roth: "Money",
	afterTax: "Money",
	compensation: "Money",
	remainingRothTarget: "Money",
	remainingAfterTaxTarget: "Money",
	deferralsRemaining: "Money",
	additionsRemaining: "Money",
	dollarCeilingRemaining: "Money",
	distributed: "Money",
	returned: "Money",
	net: "Money",
	afterTaxFunded: "Money",
	attributed: "Money",
	liability: "Money",
	observed: "Money",
	explained: "Money",
	difference: "Money",
	adjustment: "Money",
	outstanding: "Money",
	remaining: "Money",
	deducted: "Money",
	grossCents: "Money",
	rothCents: "Money",
	principal: "Money",
	// Money ranges: half-open cent intervals on the wage axis.
	earning: "MoneyRange",
	eligible: "MoneyRange",
	domain: "MoneyRange",
	wages: "MoneyRange",
	actionable: "MoneyRange",
	// Civil dates: Unix epoch days inside, "YYYY-MM-DD" at the boundary.
	asOf: "Day",
	convertedOn: "Day",
	dueOn: "Day",
	endsBefore: "Day",
	mailedOn: "Day",
	observedOn: "Day",
	opensOn: "Day",
	recordingDay: "Day",
	sentOn: "Day",
	settlesOn: "Day",
	signedOn: "Day",
	startsOn: "Day",
	submittedOn: "Day",
	receivedOn: "Day",
	effectiveOn: "Day",
	// One civil date, stored either as a day or as the fixed one-day interval.
	paidOn: "DayPoint",
	day: "DayPoint",
	authorizedOn: "DayPoint",
	// Half-open civil-date intervals: {start, endExclusive}.
	effective: "DayRange",
	period: "DayRange",
	span: "DayRange",
	valid: "DayRange",
	work: "DayRange",
	// Plain integers.
	year: "Count",
	quarter: "Count",
	denominator: "Count",
	numerator: "Count",
	length: "Count",
	ordinal: "Count",
	requiredCount: "Count",
	row: "Count",
	sequence: "Count",
	dataRevision: "Count",
	seq: "Count",
	receiptEpoch: "Count",
	added: "Count",
	removed: "Count",
	objects: "Count",
	bytes: "Count",
	wageCount: "Count",
	total: "Count",
	missingEntries: "Count",
	wagesCovered: "Count"
} as const

export type Unit = (typeof unitOf)[keyof typeof unitOf]
export const unitFor = (name: string): Unit | undefined =>
	Object.hasOwn(unitOf, name) ? unitOf[name as keyof typeof unitOf] : undefined
